-- MySQL Script generated by MySQL Workbench
-- Sun Apr  9 12:16:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema diapasong_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema diapasong_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diapasong_db` DEFAULT CHARACTER SET utf8 ;
USE `diapasong_db` ;

-- -----------------------------------------------------
-- Table `diapasong_db`.`product_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diapasong_db`.`product_type` (
  `id` TINYINT(1) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(55) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diapasong_db`.`condition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diapasong_db`.`condition` (
  `id` TINYINT(1) NOT NULL AUTO_INCREMENT,
  `condition` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diapasong_db`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diapasong_db`.`category` (
  `id` TINYINT(1) NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diapasong_db`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diapasong_db`.`color` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(55) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diapasong_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diapasong_db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_product_type` TINYINT(1) NOT NULL,
  `id_condition` TINYINT(1) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `subtitle` VARCHAR(100) NOT NULL,
  `id_category` TINYINT(1) NOT NULL,
  `description` TEXT(255) NOT NULL,
  `id_color` INT NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  `stock` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_product_type_idx` (`id_product_type` ASC) VISIBLE,
  INDEX `fk_id_condition_idx` (`id_condition` ASC) VISIBLE,
  INDEX `fk_category_idx` (`id_category` ASC) VISIBLE,
  INDEX `fk_id_color_idx` (`id_color` ASC) VISIBLE,
  CONSTRAINT `fk_id_product_type`
    FOREIGN KEY (`id_product_type`)
    REFERENCES `diapasong_db`.`product_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_condition`
    FOREIGN KEY (`id_condition`)
    REFERENCES `diapasong_db`.`condition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_category`
    FOREIGN KEY (`id_category`)
    REFERENCES `diapasong_db`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_color`
    FOREIGN KEY (`id_color`)
    REFERENCES `diapasong_db`.`color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diapasong_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diapasong_db`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `roles` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diapasong_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diapasong_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `profile_image` VARCHAR(100) NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `identifyid` INT NOT NULL,
  `birthdate` DATE NOT NULL,
  `phone` INT NULL,
  `id_genres` INT NULL,
  `id_instruments` INT NULL,
  `news` TINYINT(1) NULL,
  `terms` TINYINT(1) NOT NULL,
  `id_rol` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_rol_idx` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_id_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `diapasong_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diapasong_db`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diapasong_db`.`genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diapasong_db`.`users_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diapasong_db`.`users_genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_genre` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_id_genre_idx` (`id_genre` ASC) VISIBLE,
  CONSTRAINT `fk_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `diapasong_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_genre`
    FOREIGN KEY (`id_genre`)
    REFERENCES `diapasong_db`.`genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diapasong_db`.`instruments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diapasong_db`.`instruments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `instrument` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diapasong_db`.`users_instruments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diapasong_db`.`users_instruments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_instrument` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_id_instrument_idx` (`id_instrument` ASC) VISIBLE,
  CONSTRAINT `fk_id_user0`
    FOREIGN KEY (`id_user`)
    REFERENCES `diapasong_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_instrument`
    FOREIGN KEY (`id_instrument`)
    REFERENCES `diapasong_db`.`instruments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diapasong_db`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diapasong_db`.`payment_method` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `method` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diapasong_db`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diapasong_db`.`sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `id_user` INT NOT NULL,
  `id_payment_method` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_id_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_payment_method_idx` (`id_payment_method` ASC) VISIBLE,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`id_user`)
    REFERENCES `diapasong_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_method`
    FOREIGN KEY (`id_payment_method`)
    REFERENCES `diapasong_db`.`payment_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diapasong_db`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diapasong_db`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_product` INT NOT NULL,
  `units` INT NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  `id_sale` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_product_idx` (`id_product` ASC) VISIBLE,
  INDEX `fk_id_sale_idx` (`id_sale` ASC) VISIBLE,
  CONSTRAINT `fk_id_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `diapasong_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_sale`
    FOREIGN KEY (`id_sale`)
    REFERENCES `diapasong_db`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diapasong_db`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diapasong_db`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `id_product` INT NOT NULL,
  `main` TINYINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_product_idx` (`id_product` ASC) VISIBLE,
  CONSTRAINT `fk_id_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `diapasong_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diapasong_db`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diapasong_db`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diapasong_db`.`status_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diapasong_db`.`status_cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_status` INT NOT NULL,
  `id_cart` INT NOT NULL,
  `id_sale` INT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_cart_idx` (`id_cart` ASC) VISIBLE,
  INDEX `fk_id_status_idx` (`id_status` ASC) VISIBLE,
  INDEX `fk_id_sale_idx` (`id_sale` ASC) VISIBLE,
  CONSTRAINT `fk_id_cart`
    FOREIGN KEY (`id_cart`)
    REFERENCES `diapasong_db`.`carts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_status`
    FOREIGN KEY (`id_status`)
    REFERENCES `diapasong_db`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_sale`
    FOREIGN KEY (`id_sale`)
    REFERENCES `diapasong_db`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diapasong_db`.`payment_method_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diapasong_db`.`payment_method_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_payment_method` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_payment_method_idx` (`id_payment_method` ASC) VISIBLE,
  CONSTRAINT `fk_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `diapasong_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_method`
    FOREIGN KEY (`id_payment_method`)
    REFERENCES `diapasong_db`.`payment_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
